Add support for content library info modules
ansible-collections/vmware_rest_code_generator pull request #79
Opened 2021-01-12 10:44 UTC by Akasurde

##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
refresh_modules.py

2021-01-14 16:37 UTC, goneri commented
We also need to add functional tests for these new modules in https://github.com/ansible-collections/vmware.vmware_rest

2021-02-11 05:24 UTC, Akasurde commented
@goneri Could you please review and merge this? Thanks in advance.

2021-02-15 17:30 UTC, goneri requested changes
Thank you Abhijeet, I will land this PR as soon as the six import thing is resolved.

2021-02-15 17:30 UTC, goneri commented on vmware_rest_code_generator/module_utils/vmware_rest.py
> +from ansible.module_utils.six import string_types
Please don't use six. The module only works with py3.6+

2021-02-15 19:02 UTC, merged